### ISSUE TITLE
Anti DDos page returned and cause a lot of npe errors

### ISSUE THREAD

**Issue by DrOreo002** [Maximvdw/SpigotSite#15]
I've added a debug code for the Html page that got returned. And seems like it returned the 'Anti ddos by cloudflare' page

Also your spigot buyer check is not working. When I type **MrDienns** it said that the username is incorrect

https://imgur.com/a/cezl8dw

I doubt that the problem is on the code, it prob because of spigot website itself..

I'm not sure why but it only happens on certain time. Yesterday it works fine, but not today (13 July 2019)

**Comment by Maximvdw** [comment]
I am investigating it

**Comment by DrOreo002** [comment]
Thanks!, it's working fine now ;)
